# Font
font_family      JetBrainsMono Nerd Font Mono
bold_font        auto
italic_font      auto
font_size        14.0

# Colors (One Dark theme)
foreground       #abb2bf
background       #282c34
selection_foreground #ffffff
selection_background #61afef
cursor           #528bff
cursor_shape                    block
shell_integration               no-cursor
color0           #282c34
color1           #e06c75
color2           #98c379
color3           #e5c07b
color4           #61afef
color5           #c678dd
color6           #56b6c2
color7           #dcdfe4
color8           #5c6370
color9           #e06c75
color10          #98c379
color11          #e5c07b
color12          #61afef
color13          #c678dd
color14          #56b6c2
color15          #ffffff

# Transparency
background_opacity    0.95
background_blur       40

# Padding
window_padding_width 6

startup_session none

# Window behavior
remember_window_size   yes
initial_window_width   100c
initial_window_height  30c
hide_window_decorations titlebar-only

# Tabs & splits
map ctrl+shift+t new_tab
map ctrl+shift+w close_tab
map ctrl+shift+right next_tab
map ctrl+shift+left  previous_tab
map ctrl+shift+enter new_window

# Copy/paste
clipboard_control write-clipboard write-primary
map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard

