[directory]
style = "fg:#c07070"

[line_break]
disabled = false

[character]
success_symbol = "[❯](yellow)"

[time]
disabled = false
format = "[$time]($style) "
time_format = "%H:%M:%S"
style = "cyan"
